deployment:
  tasks:
    - export PATH=/opt/alt/php81/usr/bin:$PATH
    - /opt/alt/php81/usr/bin/php /home/blootjmm/Invent_website/Pos-website/composer.phar install --no-dev --optimize-autoloader
    - npm install --prefix /home/blootjmm/Invent_website/Pos-website
    - npm run build --prefix /home/blootjmm/Invent_website/Pos-website


