---
deployment:
  tasks:
    - export DEPLOYPATH=/home/blootjmm/public_html
    - /bin/cp -r ./* $DEPLOYPATH
    - /bin/cp -r ./public/* $DEPLOYPATH
    - /bin/cp .env $DEPLOYPATH/.env










































